//
// Created by Maria.Baburina on 1/26/2018.
//

#ifndef EDITORHYPERLINKSUPPORTMAYFREEZE_HEADER_H
#define EDITORHYPERLINKSUPPORTMAYFREEZE_HEADER_H
#define X
#endif //EDITORHYPERLINKSUPPORTMAYFREEZE_HEADER_H
